version: '3.3'

services:
    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        volumes:
            - ../dba:/var/lib/mysql
    php-8.1:
        build: .
        container_name: php-8.1
        environment:  
            uid: ${UID}
        user: ${UID}    
        ports: 
            - "8000:8000"
        volumes:
            - ../:/var/www/html
        command: /bin/sh -c "php -S 0.0.0.0:8000 -t public"
        depends_on: 
            - mysql


